# Variables needed for this script are stored on Travis Settings
#  - For all environments:
#    - AWS_DEFAULT_REGION
#  - For dev environment:
#    - AWS_ACCOUNT_USER_ID_DEV
#    - AWS_ACCOUNT_SECRET_DEV
#    - AWS_PROFILE_DEV
#  - For Demo environment:
#   - AWS_ACCOUNT_USER_ID_DEMO
#   - AWS_ACCOUNT_SECRET_DEMO
#   - AWS_PROFILE_DEMO
# - For Prod environment:
#   - AWS_ACCOUNT_USER_ID_PROD
#   - AWS_ACCOUNT_SECRET_PROD
#   - AWS_PROFILE_PROD

language: go

go:
  - 1.13.x

before_install:
- curl -sf https://up.apex.sh/install | sudo sh
- sudo up upgrade

install:
- go get -t ./...

script:
- go test -v ./...

deploy:
 # dev
 - provider: script
   script: make
   edge: true
   on:
      branch: master
 # demo
 - provider: script
   script: AWS_ACCESS_KEY_ID=$AWS_915001051872_ID AWS_SECRET_ACCESS_KEY=$AWS_915001051872_SECRET make demo
   edge: true
   on:
      branch: master
 # production
 - provider: script
   script: AWS_ACCESS_KEY_ID=$AWS_192458993663_ID AWS_SECRET_ACCESS_KEY=$AWS_192458993663_SECRET make prod
   edge: true
   on:
      branch: master
